### PR TITLE
Points are now clickable

### LINKED ISSUE #348: Allow point solver to add points on existing feature
Currently, clicking on an existing point won't trigger a solve request. This means a full circle cannot be created (which is useful for drawing features on roundabouts). 

image

See video at https://drive.google.com/file/d/1Rl5sfH_lFTIk18mLVs4rn1kzzuY3EslP/view

This related to the [DigitizeButtonController](https://github.com/compassinformatics/cpsi-mapview/blob/master/app/controller/button/DigitizeButtonController.js). 

Unclear if a handler has to be added to the Draw or Modify interactions.

### PR DESCRIPTION
**Pull request by simonseyock**
Resolves #348

### CODE REVIEW

**Comment by geographika** [comment]
@simonseyock - thanks for this. There seems to be an issue where each click results in two requests: the  `handleDrawEnd` calls `doAjaxRequest`, and then `handlePointClick` is fired - the new point has been added to the layer and so a second `doAjaxRequest` is triggered. I'll try and take a screencast later.

**Comment by simonseyock** [comment]
@geographika the added line should solve the issue

**Comment by geographika** [comment]
@simonseyock - unfortunately the `handlePointClick` is still called even with `evt.stopPropagation()`. Were you able to recreate?

**Comment by simonseyock** [comment]
I somehow thought I saw only one request but you are right, there are two.

**Comment by simonseyock** [comment]
I am sorry. I look into it again.

**Comment by simonseyock** [comment]
I solved this issue with using a timeout of 300 ms. I do not like it very much but openlayers does not offer a good way to do this here.

**Comment by geographika** [comment]
@simonseyock - thanks. This fixes the double request, but unfortunately breaks the context-menu - right-clicking now also triggers a request rather than showing the menu.

**Comment by simonseyock** [comment]
Yes I will fix that. The handling is a little bit of a mess. One thing is that the draw event reacts to mousedown instead of click events. This will cause the current solution to fail if the mouse button is hold longer than 300 ms. Another solution I thought of is to not do a request if the last point is within a certain pixel distance ...

**Comment by simonseyock** [comment]
I tried drawing points, deleting points and right clicking on points and on the background.

**Comment by geographika** [comment]
@simonseyock - many thanks for this - I've also tested all cases and it now works perfectly. 

I tried some debugging myself to resolve it but was trying to use `ol.events.condition.mouseActionButton(evt)` rather than `ol.events.condition.primaryAction(evt)` - I'll need to do some OL API docs reading!

**Pull request merged**
