### PR TITLE
Set minimizedWindows transparent & position it over map

### PR DESCRIPTION
**Pull request by jansule**
This is a follow up of #179 

The minimizedWindows toolbar is now transparent and was positioned over the map.

image

### CODE REVIEW

**Comment by jansule** [comment]
@geographika does this match your expectation?

**Comment by geographika** [comment]
Thanks for this @jansule. 
There is one issue at the moment - the minimised toolbar buttons are placed on top of each other when there are multiple windows. 

I tried this with the grid and the Streetview tool  (to activate this tool you need a Google API key and update app.json), although it appears any windows will minimise to the same location. 

image

**Comment by jansule** [comment]
> There is one issue at the moment - the minimised toolbar buttons are placed on top of each other when there are multiple windows.

Thanks for the info. I will take a look at that.

**Comment by jansule** [comment]
@geographika with the latest changes, the toolbar looks like this. As Ext is now handling the horizontal layouting of the toolbar, this should work regardless of the number of minimized windows.

image

**Comment by geographika** [comment]
@jansule - just tested this and it works very well. I'm happy to merge/close this. Thanks!

Just to confirm I'm not missing anything - if I'm adding this functionality to a project based on cpsi-mapview then I need to ensure the following:

1. Include `xtype: 'cmv_minimized_windows_toolbar'` within a `gx_map` component
2. Update the `Main.scss` with the .cmv_minimized_windows* styles
3. Ensure all windows in the application inherit from `CpsiMapview.view.window.MinimizableWindow`

**Comment by jansule** [comment]
@geographika yes, that is correct. Happy to hear that you are satisfied with the solution.

**Comment by chrismayer** [comment]
I just checked this out and tested. Works as expected. Thank you @jansule! Please merge at will...

**Pull request merged**
