### PR TITLE
Tracing Add-On: Support edges touching at interior points

### PR DESCRIPTION
**Pull request by JakobMiksch**
- references #560 
- This PR adds the attempt to also include edges that touch each other at the interior points.

#### TODO:
- [ ] tracing consecutively on many features does not work
- [ ] probably many edge cases not discovered yet

### CODE REVIEW

**Comment by JakobMiksch** [comment]
@geographika I did refactoring and cleanup. Also pulled the latest changes from #586  and master

**Comment by geographika** [comment]
@JakobMiksch - I think it would be good to merge this too so we can carry out full testing and log any issues/edge cases to prioritise addressing in a later phase.

**Comment by JakobMiksch** [comment]
@geographika The PR still has many edge cases. One missing feature is that tracing consecutive lines and hovering back to previous lines, does not work yet. But this should only affect cases where edges touch each other at the interior point. Feel free to merge, if this is fine for you.

**Comment by geographika** [comment]
I'm going to merge, so we can assess which edge cases are a priority. Thanks @JakobMiksch.

**Pull request merged**
